### ISSUE TITLE
Styling for focused selection background will soon need to be more specific

### ISSUE THREAD

**Issue by marijnh** [dennis84/codemirror-themes#3]
To address a bug where, if people put CodeMirror editors inside another CodeMirror editor, the outer editor's focused state affects the selection and cursor styling of the inner editors, I will soon put out a release of @codemirror/view that uses a more specific style rule for the default focused selection color. In order for themes to still override this, they will need to match the specificity.

That means that in your themes, rules for `&.cm-focused .cm-selectionBackground` must all be replaced with `&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground`.

**Comment by dennis84** [comment]
Hello @marijnh, thank you for posting this issue here to keep my project in sync. I didn't know that you knew about my project. I needed some more themes for a project of mine and created a quick generator. I work with CM and PM almost every day and update regularly and also try to keep this project updated based on one-dark from you. The issue should be fixed now, thanks!

**Comment by marijnh** [comment]
Awesome, thank you for the quick turnaround.
